# Generated by Django 4.0.6 on 2022-07-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperType',
        ),
    ]
