# Generated by Django 4.0.6 on 2022-07-18 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_rename_secondary_abliity_supers_secondary_ablility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supers',
            old_name='secondary_ablility',
            new_name='secondary_ability',
        ),
    ]
