# Generated by Django 4.0.6 on 2022-07-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_rename_secondary_ablility_supers_secondary_ability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supers',
            new_name='Super',
        ),
    ]
